github:
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  labels:
    - flink
    - jdbc
    - connector
    - datastream
    - table
    - sql
  autolink_jira: FLINK
  collaborators:
    - flinkbot
notifications:
  commits:      commits@flink.apache.org
  issues:       issues@flink.apache.org
  pullrequests: issues@flink.apache.org
  jobs:         builds@flink.apache.org
  jira_options: link label
